<a href="https://colab.research.google.com/github/shinb-bong/TIL/blob/main/Tensorflow%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

기본 tensor 만들기 
---
숫자랑 , 리스트 담는 곳이다.

In [1]:
import tensorflow as tf

tensor = tf.constant(3)
print(tensor)

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
tensor1 = tf.constant([3,4,5])
tensor2 = tf.constant([6,7,8])

print(tensor1+ tensor2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [5]:
tensor3 = tf.constant([[1,2],[3,4]])
tensor4 = tf.constant([[5,6],[7,8]])

print(tf.add(tensor3,tensor4))

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


행렬의 곱은 tf.matmul()함수를 쓰면 된다.

In [8]:
tensor5 = tf.zeros(10)
print(tensor5)

tensor6 = tf.zeros([2,2])
print(tensor6)

print(tensor6.shape)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
(2, 2)


shape 해석법 뒤에서 부터 읽어준다. 2개짜리가 2개있다.

weight 저장하고 싶으면

In [11]:
w= tf.Variable(1.0)
print(w)
print(w.numpy())

w.assign(2)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
1.0
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [12]:
키 = [170,180,175,160]
신발 = [260,270,265,255]
# 신발 = 키 * a +b

a = tf.Variable(0.1)
b = tf.Variable(0.1)

def loss_function():
  예측 =  키 * a + b
  return tf.square(신발 - 예측)
# 경사하강법
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(300):
  # 손실함수, var_list
  opt.minimize(loss_function,var_list=[a,b])
  print(a.numpy(),b.numpy())

0.19999999 0.2
0.29974356 0.29974392
0.39903092 0.39903224
0.49763483 0.49763814
0.5953028 0.59530956
0.69175315 0.69176537
0.78667295 0.7866934
0.8797197 0.87975186
0.9705204 0.9705687
1.0586745 1.0587443
1.1437569 1.1438549
1.2253246 1.2254585
1.3029255 1.3031044
1.3761085 1.3763429
1.4444377 1.4447393
1.5075065 1.5078881
1.564953 1.5654284
1.6164753 1.6170591
1.6618448 1.6625519
1.7009159 1.7017612
1.7336324 1.7346308
1.7600297 1.7611955
1.7802323 1.7815794
1.7944489 1.7959898
1.8029628 1.8047092
1.8061227 1.8080851
1.8043308 1.8065188
1.7980328 1.8004547
1.7877059 1.7903694
1.7738502 1.7767619
1.7569793 1.760145
1.7376126 1.7410374
1.7162678 1.7199563
1.6934549 1.6974112
1.66967 1.6738979
1.64539 1.6498927
1.6210672 1.6258477
1.5971242 1.6021854
1.5739497 1.579294
1.551894 1.5575236
1.531265 1.5371822
1.5123259 1.5185325
1.4952921 1.5017899
1.4803301 1.4871206
1.467557 1.4746417
1.4570407 1.4644209
1.4488019 1.4564788
1.4428159 1.4507908
1.4390163 1.4472902
1.4372988 1.4458728
1.43

In [14]:
train_x = [1,2,3,4,5,6,7]
train_y = [3,5,7,9,11,13,15]

# 모델 만들기 => 학습 순으로 진행
a = tf.Variable(0.1)
b = tf.Variable(0.1)

def loss_function(a,b):
  예측_y = train_x * a + b
  return tf.keras.losses.mse(train_y,예측_y)

# 경사하강법
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

for i in range(1000):
  # 손실함수, var_list
  opt.minimize(lambda:loss_function(a,b),var_list=[a,b])
  print(a.numpy(),b.numpy())


0.11 0.11
0.11999842 0.11999838
0.1299943 0.12999418
0.1399865 0.13998622
0.14997402 0.14997348
0.15995584 0.15995494
0.16993088 0.16992946
0.17989811 0.17989603
0.18985653 0.18985358
0.19980511 0.19980109
0.20974284 0.20973754
0.21966875 0.21966189
0.22958185 0.22957318
0.2394812 0.2394704
0.24936585 0.24935263
0.2592349 0.25921893
0.26908746 0.26906836
0.27892265 0.27890003
0.2887396 0.2887131
0.2985375 0.29850668
0.30831558 0.30828
0.31807303 0.31803223
0.32780915 0.32776266
0.3375232 0.3374705
0.34721446 0.34715506
0.3568823 0.35681567
0.36652604 0.36645162
0.3761451 0.3760623
0.38573885 0.38564712
0.39530674 0.39520547
0.40484825 0.40473682
0.41436282 0.4142406
0.42384997 0.4237163
0.43330923 0.43316346
0.44274014 0.44258162
0.4521423 0.4519703
0.46151525 0.4613291
0.47085863 0.4706576
0.48017207 0.4799554
0.4894552 0.48922217
0.49870768 0.49845755
0.5079292 0.5076612
0.51711947 0.5168328
0.5262782 0.52597207
0.5354051 0.5350787
0.5444999 0.54415244
0.55356234 0.553193
0.5625922 0

Keras
---

In [ ]:
import pandas as pd

data = pd.read_csv('경로')
print(data)

print(data.isnull().sum())
data = data.dropna()
# data.fillna(100)

# 리스트형태로 담아줌
y데이터 = data['admit'].values

x데이터 = []
for i , rows in data.iterrow():
  x데이터.append([rows['gre'], rows['gpa'],rows['rank']])

import numpy as np
import tensorflow as tf

# 실험적으로 파악해서 모델을 만들어야함
# 마지막에 오는건 이때까지 공부 한 것 처럼 주의해줘야함.
model = tf.keras.models.Sequential([
                                    tf.keras.layers.Dense(64,activation='tanh'),
                                    tf.keras.layers.Dense(128,activation='tanh'),
                                    tf.keras.layers.Dense(1,activiation='sigmoid')

])

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# 학습시키기 np.array만 넣어줄수있음
model.fit(np.array(x데이터),np.array(y데이터),epochs=10)

# 예측하기
예측값 = model.predict([[750,3.70,3],[400,2.2,1]])
print(예측값)

1. 모델을 만든다.
2. 데이터 집어넣고 학습
3. 새로운 데이터 예측
 
+데이터 전처리
+파라미터 튜닝